### ISSUE TITLE
FR: Download and update CSS snippets 

### ISSUE THREAD

**Issue by efemkay** [mwoz123/swiss-army-knife-obsidian#2]
https://github.com/Lisandra-dev/obsidian-snippet-downloader

This plugin was recently archived and will not be maintained anymore. Any chance u can CSS snippets downloader and updater?

**Comment by mwoz123** [comment]
I've no plans at the moment. 

Probably it won't help you much but with latest S.A.K.O. version you should be able to download any (even archived) plugin version...

**Comment by efemkay** [comment]
No worries. Just trying my luck. Currently I can install the plugin via BRAT
